//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsyncTaskInfo
    {
        public long Id { get; set; }
        public int TypeEn { get; set; }
        public string Param1 { get; set; }
        public string Param2 { get; set; }
        public string Param3 { get; set; }
        public long StatusId { get; set; }
        public Nullable<long> ErrorId { get; set; }
        public string ExceptionType { get; set; }
        public string ExceptionMessage { get; set; }
        public System.DateTime InsDate { get; set; }
        public byte[] RV { get; set; }
        public bool IsDeleted { get; set; }
        public long InsOperId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
    
        public virtual Error Error { get; set; }
        public virtual TaskStatus TaskStatus { get; set; }
    }
}
