//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Card()
        {
            this.Card1 = new HashSet<Card>();
            this.CardImageItem = new HashSet<CardImageItem>();
            this.CardProfile = new HashSet<CardProfile>();
            this.Control = new HashSet<Control>();
            this.Gemalto = new HashSet<Gemalto>();
            this.GreenList = new HashSet<GreenList>();
            this.GreyList = new HashSet<GreyList>();
            this.Operator = new HashSet<Operator>();
            this.Order = new HashSet<Order>();
            this.ProfileCard = new HashSet<ProfileCard>();
            this.SaleDetail = new HashSet<SaleDetail>();
            this.StockMovement = new HashSet<StockMovement>();
        }
    
        public long Id { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<long> CardStatusId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<long> MediaTypeId { get; set; }
        public Nullable<long> CardTypeId { get; set; }
        public long CompanyId { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<System.DateTime> LastValidationDate { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
        public byte[] RV { get; set; }
        public bool IsActive { get; set; }
        public string BoxId { get; set; }
        public Nullable<long> ProviderId { get; set; }
        public Nullable<long> StockEntityDetailId { get; set; }
        public Nullable<System.Guid> ImportId { get; set; }
        public Nullable<long> DuplicataId { get; set; }
        public Nullable<System.DateTime> DuplicataDate { get; set; }
        public Nullable<long> DuplicataReasonId { get; set; }
    
        public virtual CardStatus CardStatus { get; set; }
        public virtual CardType CardType { get; set; }
        public virtual Company Company { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card> Card1 { get; set; }
        public virtual Card Card2 { get; set; }
        public virtual DuplicataReason DuplicataReason { get; set; }
        public virtual MediaType MediaType { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual StockEntityDetail StockEntityDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardImageItem> CardImageItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardProfile> CardProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Control> Control { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gemalto> Gemalto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GreenList> GreenList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GreyList> GreyList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operator> Operator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileCard> ProfileCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleDetail> SaleDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockMovement> StockMovement { get; set; }
    }
}
