//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardImageItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CardImageItem()
        {
            this.Gemalto = new HashSet<Gemalto>();
        }
    
        public long Id { get; set; }
        public long CardId { get; set; }
        public long FareProductItemId { get; set; }
        public Nullable<long> Tcn { get; set; }
        public Nullable<long> StatusId { get; set; }
        public Nullable<System.DateTime> FirstValidationDate { get; set; }
        public Nullable<int> NumberOfTrips { get; set; }
        public Nullable<System.DateTime> StartValidityDate { get; set; }
        public Nullable<System.DateTime> EndValidityDate { get; set; }
        public bool IsValid { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] RV { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual CardContractStatus CardContractStatus { get; set; }
        public virtual FareProductItem FareProductItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gemalto> Gemalto { get; set; }
    }
}
