//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardTypeMediaType
    {
        public long Id { get; set; }
        public long CardTypeId { get; set; }
        public long MediaTypeId { get; set; }
        public System.DateTime ModDate { get; set; }
        public long ModOperId { get; set; }
        public byte[] RV { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
    
        public virtual CardType CardType { get; set; }
        public virtual MediaType MediaType { get; set; }
    }
}
