//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Context
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Context()
        {
            this.PublishedContext = new HashSet<PublishedContext>();
            this.PublishedContext1 = new HashSet<PublishedContext>();
        }
    
        public long Id { get; set; }
        public string Description { get; set; }
        public long FareVersionId { get; set; }
        public long TopologyVersionId { get; set; }
        public long TopologyPeriodId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public long StatusId { get; set; }
        public long InsOperId { get; set; }
        public System.DateTime InsDate { get; set; }
        public byte[] RV { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual FareVersion FareVersion { get; set; }
        public virtual Status Status { get; set; }
        public virtual TopologyPeriod TopologyPeriod { get; set; }
        public virtual TopologyVersion TopologyVersion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublishedContext> PublishedContext { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublishedContext> PublishedContext1 { get; set; }
    }
}
