//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control
    {
        public long Id { get; set; }
        public long SessionId { get; set; }
        public long TCN { get; set; }
        public long ProductIssuerId { get; set; }
        public Nullable<long> FareProductItemId { get; set; }
        public Nullable<long> ProductCode { get; set; }
        public long OperatorId { get; set; }
        public long ControlTypeId { get; set; }
        public long VehicleId { get; set; }
        public Nullable<long> LineId { get; set; }
        public Nullable<long> ItineraryId { get; set; }
        public int Direction { get; set; }
        public Nullable<long> FareStopId { get; set; }
        public System.DateTime ControlDate { get; set; }
        public Nullable<long> CardId { get; set; }
        public Nullable<long> TicketId { get; set; }
        public Nullable<System.DateTime> ProductStartValidity { get; set; }
        public Nullable<System.DateTime> ProductEndOfValidity { get; set; }
        public long ControlStatusId { get; set; }
        public Nullable<long> FineId { get; set; }
        public byte[] RV { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual ControlStatus ControlStatus { get; set; }
        public virtual ControlType ControlType { get; set; }
        public virtual FareProductItem FareProductItem { get; set; }
        public virtual FareStop FareStop { get; set; }
        public virtual Fine Fine { get; set; }
        public virtual Itinerary Itinerary { get; set; }
        public virtual Line Line { get; set; }
        public virtual Operator Operator { get; set; }
        public virtual Session Session { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
