//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerContactPhone
    {
        public long Id { get; set; }
        public long CustomerId { get; set; }
        public long ContactTypeId { get; set; }
        public string Prefix { get; set; }
        public string CallNumber { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] RV { get; set; }
        public bool IsValid { get; set; }
        public bool SMS { get; set; }
        public bool Call { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
    
        public virtual ContactType ContactType { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
