//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Card = new HashSet<Card>();
            this.CompanyAdditionalInformation = new HashSet<CompanyAdditionalInformation>();
            this.CompanyPreferredContact = new HashSet<CompanyPreferredContact>();
            this.CustomerAddress = new HashSet<CustomerAddress>();
            this.CustomerAdditionalInformation = new HashSet<CustomerAdditionalInformation>();
            this.CustomerBankAccount = new HashSet<CustomerBankAccount>();
            this.CustomerCustGroup = new HashSet<CustomerCustGroup>();
            this.CustomerCompany = new HashSet<CustomerCompany>();
            this.CustomerContactPhone = new HashSet<CustomerContactPhone>();
            this.CustomerContactEmail = new HashSet<CustomerContactEmail>();
            this.CustomerDocument = new HashSet<CustomerDocument>();
            this.CustomerNote = new HashSet<CustomerNote>();
            this.CustomerPayer = new HashSet<CustomerPayer>();
            this.CustomerProfile = new HashSet<CustomerProfile>();
            this.CustomerProfessionalCategory = new HashSet<CustomerProfessionalCategory>();
            this.CustomerPayer1 = new HashSet<CustomerPayer>();
            this.CustomerRelation = new HashSet<CustomerRelation>();
            this.CustomerRelation1 = new HashSet<CustomerRelation>();
            this.Device = new HashSet<Device>();
            this.FareProductItemCustomer = new HashSet<FareProductItemCustomer>();
            this.Gemalto = new HashSet<Gemalto>();
            this.Operator = new HashSet<Operator>();
            this.Order = new HashSet<Order>();
            this.Sale = new HashSet<Sale>();
        }
    
        public long Id { get; set; }
        public long CustomerTypeId { get; set; }
        public Nullable<long> TitleId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long GenderId { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string NationalityCode { get; set; }
        public Nullable<long> MaritalStatusId { get; set; }
        public Nullable<long> PreferredContactTypeId { get; set; }
        public Nullable<long> SchoolLevelId { get; set; }
        public Nullable<long> SchoolId { get; set; }
        public byte[] Photo { get; set; }
        public bool Bdx_Modibus { get; set; }
        public bool Vcub { get; set; }
        public bool Bdx_NewsletterEnterprise { get; set; }
        public bool Bdx_Newsletter1 { get; set; }
        public bool Bdx_Newsletter2 { get; set; }
        public bool Bdx_Newsletter3 { get; set; }
        public bool AllowPhotoCapture { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] RV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card> Card { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyAdditionalInformation> CompanyAdditionalInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyPreferredContact> CompanyPreferredContact { get; set; }
        public virtual CustomerType CustomerType { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual MaritalStatusType MaritalStatusType { get; set; }
        public virtual PreferredContactType PreferredContactType { get; set; }
        public virtual SchoolLevel SchoolLevel { get; set; }
        public virtual School School { get; set; }
        public virtual PeopleTitleType PeopleTitleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerAddress> CustomerAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerAdditionalInformation> CustomerAdditionalInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerBankAccount> CustomerBankAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCustGroup> CustomerCustGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCompany> CustomerCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerContactPhone> CustomerContactPhone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerContactEmail> CustomerContactEmail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerDocument> CustomerDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerNote> CustomerNote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPayer> CustomerPayer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerProfile> CustomerProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerProfessionalCategory> CustomerProfessionalCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPayer> CustomerPayer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerRelation> CustomerRelation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerRelation> CustomerRelation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FareProductItemCustomer> FareProductItemCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gemalto> Gemalto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operator> Operator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sale { get; set; }
    }
}
