//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceParam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeviceParam()
        {
            this.DeviceConfigParam = new HashSet<DeviceConfigParam>();
        }
    
        public long Id { get; set; }
        public Nullable<long> DeviceTypeId { get; set; }
        public string Section { get; set; }
        public string Name { get; set; }
        public long TypeId { get; set; }
        public string DefaultValue { get; set; }
        public bool IsMandatory { get; set; }
        public byte[] RV { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceConfigParam> DeviceConfigParam { get; set; }
        public virtual DeviceType DeviceType { get; set; }
        public virtual DeviceParamType DeviceParamType { get; set; }
    }
}
