//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportedFile
    {
        public long Id { get; set; }
        public Nullable<long> VehicleId { get; set; }
        public Nullable<long> DeviceId { get; set; }
        public long PublishedContextId { get; set; }
        public string OperatorListFileName { get; set; }
        public string BlackListFileName { get; set; }
        public string GreyListFileName { get; set; }
        public string GreenListFileName { get; set; }
        public string ConfigFileName { get; set; }
        public string CurrentTopologyFileName { get; set; }
        public string CurrentProductListFileName { get; set; }
        public string CurrentProfileListFileName { get; set; }
        public string CurrentFineListFileName { get; set; }
        public System.DateTime CurrentContextApplyDate { get; set; }
        public string FutureTopologyFileName { get; set; }
        public string FutureProductListFileName { get; set; }
        public string FutureProfileListFileName { get; set; }
        public string FutureFineListFileName { get; set; }
        public System.DateTime FutureContextApplyDate { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public byte[] RV { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual PublishedContext PublishedContext { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
