//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FareVersion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FareVersion()
        {
            this.Context = new HashSet<Context>();
            this.FareProductItem = new HashSet<FareProductItem>();
            this.IncompatibilityMatrix = new HashSet<IncompatibilityMatrix>();
        }
    
        public long Id { get; set; }
        public string Description { get; set; }
        public long StatusId { get; set; }
        public Nullable<long> DefaultTaxId { get; set; }
        public long InsOperId { get; set; }
        public System.DateTime InsDate { get; set; }
        public byte[] RV { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Context> Context { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FareProductItem> FareProductItem { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncompatibilityMatrix> IncompatibilityMatrix { get; set; }
        public virtual Tax Tax { get; set; }
    }
}
