//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FareProductItemDescription
    {
        public long Id { get; set; }
        public long FareProductItemId { get; set; }
        public string LanguageCode { get; set; }
        public string CommercialName { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string Info { get; set; }
        public string ValidationOk { get; set; }
        public string ValidationKo { get; set; }
        public string ImpressLabel3 { get; set; }
        public string ImpressLabel2 { get; set; }
        public string ImpressLabel1 { get; set; }
        public string ImpressLabel { get; set; }
        public string ImpressInfo3 { get; set; }
        public string ImpressInfo2 { get; set; }
        public string ImpressInfo1 { get; set; }
        public string ImpressInfo { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public byte[] RV { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
    
        public virtual FareProductItem FareProductItem { get; set; }
        public virtual Language Language { get; set; }
    }
}
