//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fine()
        {
            this.Control = new HashSet<Control>();
            this.RegularizedFine = new HashSet<RegularizedFine>();
        }
    
        public long Id { get; set; }
        public long FineNum { get; set; }
        public System.DateTime FineDate { get; set; }
        public long FineStatusId { get; set; }
        public int Amount { get; set; }
        public Nullable<long> DeclaredActorId { get; set; }
        public Nullable<long> IdentifiedActorId { get; set; }
        public Nullable<long> GeneralConsuelId { get; set; }
        public string Note { get; set; }
        public string Signature { get; set; }
        public Nullable<long> FineCancellationReasonId { get; set; }
        public string ReasonOfTheCancelled { get; set; }
        public string Justificatory { get; set; }
        public Nullable<long> FineReasonId { get; set; }
        public Nullable<long> SaleId { get; set; }
        public bool TitanFraude { get; set; }
        public byte[] RV { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Control> Control { get; set; }
        public virtual FineActor FineActor { get; set; }
        public virtual FineCancellationReason FineCancellationReason { get; set; }
        public virtual FineReason FineReason { get; set; }
        public virtual FineStatus FineStatus { get; set; }
        public virtual FineActor FineActor1 { get; set; }
        public virtual FineActor FineActor2 { get; set; }
        public virtual Sale Sale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegularizedFine> RegularizedFine { get; set; }
    }
}
