//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreenListErrorOnMedia
    {
        public long Id { get; set; }
        public Nullable<long> OperatorId { get; set; }
        public long DeviceId { get; set; }
        public System.DateTime ActionDate { get; set; }
        public byte ErrorReasonwriteOnMediaId { get; set; }
        public long GreenListId { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
        public byte[] RV { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual ErrorReasonWriteOnMedia ErrorReasonWriteOnMedia { get; set; }
        public virtual GreenList GreenList { get; set; }
        public virtual Operator Operator { get; set; }
    }
}
