//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreyList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GreyList()
        {
            this.GreyListErrorOnMedia = new HashSet<GreyListErrorOnMedia>();
        }
    
        public long Id { get; set; }
        public long CardId { get; set; }
        public long FareProductItemId { get; set; }
        public long Tcn { get; set; }
        public long ActionTypeId { get; set; }
        public System.DateTime ActionDate { get; set; }
        public long ReasonId { get; set; }
        public Nullable<long> DeviceId { get; set; }
        public bool AckReceived { get; set; }
        public Nullable<System.DateTime> AckDate { get; set; }
        public Nullable<long> AckDeviceId { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
        public byte[] RV { get; set; }
        public Nullable<long> OperatorId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Device Device { get; set; }
        public virtual Device Device1 { get; set; }
        public virtual FareProductItem FareProductItem { get; set; }
        public virtual GreyListActionType GreyListActionType { get; set; }
        public virtual Operator Operator { get; set; }
        public virtual GreyListReason GreyListReason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GreyListErrorOnMedia> GreyListErrorOnMedia { get; set; }
    }
}
