//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncompatibilityMatrix
    {
        public long Id { get; set; }
        public long FareProductItem1Id { get; set; }
        public long FareProductItem2Id { get; set; }
        public long InsOperId { get; set; }
        public System.DateTime InsDate { get; set; }
        public byte[] RV { get; set; }
        public long FareVersionId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
    
        public virtual FareProductItem FareProductItem { get; set; }
        public virtual FareProductItem FareProductItem1 { get; set; }
        public virtual FareVersion FareVersion { get; set; }
    }
}
