//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallmentRenewed
    {
        public long Id { get; set; }
        public long OldPlanId { get; set; }
        public long NewPlanId { get; set; }
        public long OldFareProductItemId { get; set; }
        public long NewFareProductItemId { get; set; }
        public bool IsPrinted { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsPriceChanged { get; set; }
        public System.DateTime RenewedDate { get; set; }
    
        public virtual FareProductItem FareProductItem { get; set; }
        public virtual FareProductItem FareProductItem1 { get; set; }
        public virtual Installment Installment { get; set; }
        public virtual Installment Installment1 { get; set; }
    }
}
