//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallmentDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstallmentDetail()
        {
            this.InstallmentDetail1 = new HashSet<InstallmentDetail>();
        }
    
        public long Id { get; set; }
        public long InstalmentId { get; set; }
        public Nullable<long> SaleDetailId { get; set; }
        public long StatusId { get; set; }
        public Nullable<long> StatusReasonId { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int PaymentAmount { get; set; }
        public string SepaTraceCode { get; set; }
        public Nullable<long> RejectSaleDetailId { get; set; }
        public Nullable<System.DateTime> RejectDate { get; set; }
        public Nullable<long> RejectReasonId { get; set; }
        public Nullable<long> AnnexInstallmentDetailId { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] RV { get; set; }
    
        public virtual Installment Installment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallmentDetail> InstallmentDetail1 { get; set; }
        public virtual InstallmentDetail InstallmentDetail2 { get; set; }
        public virtual InstallmentRejectReason InstallmentRejectReason { get; set; }
        public virtual SaleDetail SaleDetail { get; set; }
        public virtual SaleDetail SaleDetail1 { get; set; }
        public virtual InstallmentStatusReason InstallmentStatusReason { get; set; }
        public virtual InstallmentStatus InstallmentStatus { get; set; }
    }
}
