//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallmentConfiguration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstallmentConfiguration()
        {
            this.Installment = new HashSet<Installment>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public long RoundTypeId { get; set; }
        public int Periodicity { get; set; }
        public int NumberOfInstallment { get; set; }
        public int NumberOfInstallmentToBePaidInCash { get; set; }
        public int RoundingInstallmentIndex { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public byte[] RV { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Installment> Installment { get; set; }
        public virtual RoundType RoundType { get; set; }
    }
}
