//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Installment()
        {
            this.Installment1 = new HashSet<Installment>();
            this.InstallmentDetail = new HashSet<InstallmentDetail>();
            this.InstallmentRenewed = new HashSet<InstallmentRenewed>();
            this.InstallmentRenewed1 = new HashSet<InstallmentRenewed>();
        }
    
        public long Id { get; set; }
        public long PaymentOrderId { get; set; }
        public long SaleDetailId { get; set; }
        public Nullable<long> InstallmentConfigurationId { get; set; }
        public long PlanStatusId { get; set; }
        public Nullable<System.DateTime> ChangeStatusDate { get; set; }
        public Nullable<long> AnnexedInstallmentId { get; set; }
        public bool IsRenewable { get; set; }
        public Nullable<System.DateTime> EndValidityDate { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
        public byte[] RV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Installment> Installment1 { get; set; }
        public virtual Installment Installment2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallmentDetail> InstallmentDetail { get; set; }
        public virtual InstallmentConfiguration InstallmentConfiguration { get; set; }
        public virtual PaymentOrder PaymentOrder { get; set; }
        public virtual InstallmentPlanStatus InstallmentPlanStatus { get; set; }
        public virtual SaleDetail SaleDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallmentRenewed> InstallmentRenewed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallmentRenewed> InstallmentRenewed1 { get; set; }
    }
}
