//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineTopology
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LineTopology()
        {
            this.Itinerary = new HashSet<Itinerary>();
        }
    
        public long Id { get; set; }
        public long LineId { get; set; }
        public long TopologyId { get; set; }
        public Nullable<long> TopologyPeriodId { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] RV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Itinerary> Itinerary { get; set; }
        public virtual Line Line { get; set; }
        public virtual Topology Topology { get; set; }
        public virtual TopologyPeriod TopologyPeriod { get; set; }
        public virtual LineTopology LineTopology1 { get; set; }
        public virtual LineTopology LineTopology2 { get; set; }
    }
}
