//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_detail()
        {
            this.GreenList = new HashSet<GreenList>();
            this.OrderDetail_Document = new HashSet<OrderDetail_Document>();
        }
    
        public long Id { get; set; }
        public long OrderId { get; set; }
        public Nullable<long> FareProductItemId { get; set; }
        public Nullable<long> ProfileId { get; set; }
        public Nullable<byte> StatusId { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
        public byte[] RV { get; set; }
    
        public virtual FareProductItem FareProductItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GreenList> GreenList { get; set; }
        public virtual Order Order { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual Order_status Order_status { get; set; }
        public virtual Order_detail Order_detail1 { get; set; }
        public virtual Order_detail Order_detail2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail_Document> OrderDetail_Document { get; set; }
    }
}
