//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail_Document
    {
        public long Id { get; set; }
        public long SupportDocumentId { get; set; }
        public string DocumentUrl { get; set; }
        public long OrderDetailId { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual Order_detail Order_detail { get; set; }
        public virtual SupportDocument SupportDocument { get; set; }
    }
}
