//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_detail = new HashSet<Order_detail>();
        }
    
        public long Id { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<long> CardId { get; set; }
        public Nullable<byte> StatusId { get; set; }
        public Nullable<long> BillingAddress { get; set; }
        public Nullable<long> DeliveryAddress { get; set; }
        public System.DateTime OrderDate { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
        public byte[] RV { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Customer_OrderAddress Customer_OrderAddress { get; set; }
        public virtual Customer_OrderAddress Customer_OrderAddress1 { get; set; }
        public virtual Order_status Order_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_detail> Order_detail { get; set; }
    }
}
