//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class OriginDestinationRestriction
    {
        public long Id { get; set; }
        public long GeographicalRestrictionId { get; set; }
        public long OriginId { get; set; }
        public long DestinationId { get; set; }
        public Nullable<long> ViaId { get; set; }
        public Nullable<long> LineId { get; set; }
        public long InsOperId { get; set; }
        public System.DateTime InsDate { get; set; }
        public byte[] RV { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
    
        public virtual FareStop FareStop { get; set; }
        public virtual FareStop FareStop1 { get; set; }
        public virtual FareStop FareStop2 { get; set; }
        public virtual GeographicalRestriction GeographicalRestriction { get; set; }
        public virtual Line Line { get; set; }
    }
}
