//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.BanknoteTypeSale = new HashSet<BanknoteTypeSale>();
            this.RegularizedFine = new HashSet<RegularizedFine>();
        }
    
        public long Id { get; set; }
        public long PaymentMethodId { get; set; }
        public Nullable<long> SaleDetailId { get; set; }
        public string ReferenceNumber { get; set; }
        public int Amount { get; set; }
        public int Return { get; set; }
        public Nullable<long> TicketPrejudiceId { get; set; }
        public byte[] RV { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BanknoteTypeSale> BanknoteTypeSale { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual SaleDetail SaleDetail { get; set; }
        public virtual TicketPrejudice TicketPrejudice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegularizedFine> RegularizedFine { get; set; }
    }
}
