//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profile()
        {
            this.CustomerProfile = new HashSet<CustomerProfile>();
            this.FareProductItemProfile = new HashSet<FareProductItemProfile>();
            this.GreenList = new HashSet<GreenList>();
            this.Order_detail = new HashSet<Order_detail>();
            this.ProfileCard = new HashSet<ProfileCard>();
            this.ProfileDescription = new HashSet<ProfileDescription>();
            this.SupportDocument = new HashSet<SupportDocument>();
        }
    
        public long Id { get; set; }
        public long Code { get; set; }
        public string Description { get; set; }
        public long ProfileTypeId { get; set; }
        public bool Encoding { get; set; }
        public bool IsDistributableElectronically { get; set; }
        public Nullable<long> ValidityTypeId { get; set; }
        public Nullable<long> ValidityPeriodTypeId { get; set; }
        public Nullable<int> ValidityCount { get; set; }
        public Nullable<System.DateTime> StartValidity { get; set; }
        public Nullable<System.DateTime> EndValidity { get; set; }
        public bool IsRestorable { get; set; }
        public bool IsRenewable { get; set; }
        public bool IsSuppressible { get; set; }
        public Nullable<int> StartAge { get; set; }
        public Nullable<int> EndAge { get; set; }
        public long InsOperId { get; set; }
        public System.DateTime InsDate { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] RV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerProfile> CustomerProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FareProductItemProfile> FareProductItemProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GreenList> GreenList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_detail> Order_detail { get; set; }
        public virtual PeriodType PeriodType { get; set; }
        public virtual ProfileType ProfileType { get; set; }
        public virtual ProfileValidityType ProfileValidityType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileCard> ProfileCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileDescription> ProfileDescription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportDocument> SupportDocument { get; set; }
    }
}
