//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublishedContext
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PublishedContext()
        {
            this.ExportedFile = new HashSet<ExportedFile>();
        }
    
        public long Id { get; set; }
        public long CurrentContextId { get; set; }
        public long FutureContextId { get; set; }
        public System.DateTime SwitchDate { get; set; }
        public Nullable<long> DeviceId { get; set; }
        public Nullable<long> VehicleId { get; set; }
        public Nullable<long> DeviceConfigurationId { get; set; }
        public bool IsExported { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public byte[] RV { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
    
        public virtual Context Context { get; set; }
        public virtual Context Context1 { get; set; }
        public virtual Device Device { get; set; }
        public virtual DeviceConfiguration DeviceConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExportedFile> ExportedFile { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
