//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.CoinTypeSale = new HashSet<CoinTypeSale>();
            this.Fine = new HashSet<Fine>();
            this.SaleDetail = new HashSet<SaleDetail>();
            this.TicketPrejudice = new HashSet<TicketPrejudice>();
        }
    
        public long Id { get; set; }
        public long SessionId { get; set; }
        public long OperatorId { get; set; }
        public long TransactionNumber { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int TotalAmount { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<long> SaleStatusId { get; set; }
        public int NumberOfRequestedProducts { get; set; }
        public int NumberOfDeliveredProducts { get; set; }
        public int AmountOfRequestedProducts { get; set; }
        public int AmountOfDeliveredProducts { get; set; }
        public int AmountOfDamagedTickets { get; set; }
        public int AmountOfPaymentIncidents { get; set; }
        public string ReceiptId { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public byte[] RV { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoinTypeSale> CoinTypeSale { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fine> Fine { get; set; }
        public virtual Operator Operator { get; set; }
        public virtual SaleStatus SaleStatus { get; set; }
        public virtual Session Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleDetail> SaleDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketPrejudice> TicketPrejudice { get; set; }
    }
}
