//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleDetail()
        {
            this.GreenList = new HashSet<GreenList>();
            this.Installment = new HashSet<Installment>();
            this.InstallmentDetail = new HashSet<InstallmentDetail>();
            this.InstallmentDetail1 = new HashSet<InstallmentDetail>();
            this.Payment = new HashSet<Payment>();
            this.PostPayment = new HashSet<PostPayment>();
        }
    
        public long Id { get; set; }
        public long SaleId { get; set; }
        public long Tcn { get; set; }
        public long FareProductItemId { get; set; }
        public Nullable<long> RechargeCode { get; set; }
        public long ProductIssuerId { get; set; }
        public Nullable<long> TicketId { get; set; }
        public Nullable<long> CardId { get; set; }
        public int NumberOfRequested { get; set; }
        public int NumberOfDelivered { get; set; }
        public int UnitPrice { get; set; }
        public int TotalPrice { get; set; }
        public long TaxId { get; set; }
        public string DiscountCode { get; set; }
        public Nullable<int> DiscountAmount { get; set; }
        public Nullable<long> LineId { get; set; }
        public Nullable<long> OriginId { get; set; }
        public Nullable<long> DestinationId { get; set; }
        public Nullable<long> OriginZoneId { get; set; }
        public Nullable<long> DestinationZoneId { get; set; }
        public Nullable<System.DateTime> ProductStartValidity { get; set; }
        public Nullable<System.DateTime> ProductEndOfValidity { get; set; }
        public Nullable<long> SaleStatusId { get; set; }
        public Nullable<long> SaleTypeId { get; set; }
        public bool IsRefound { get; set; }
        public byte[] RV { get; set; }
        public bool IsNewCardIssue { get; set; }
        public Nullable<long> TicketPrejudiceId { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual FareProductItem FareProductItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GreenList> GreenList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Installment> Installment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallmentDetail> InstallmentDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallmentDetail> InstallmentDetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostPayment> PostPayment { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual Tax Tax { get; set; }
        public virtual TicketPrejudice TicketPrejudice { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
