//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleExportView
    {
        public long DeviceId { get; set; }
        public string DeviceType { get; set; }
        public string DeviceDescription { get; set; }
        public int SessionNumber { get; set; }
        public long OperatorId { get; set; }
        public long TransactionNumber { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int SaleTotalAmount { get; set; }
        public double TaxPercentage { get; set; }
        public int SaleDetailUnitPrice { get; set; }
        public int SaleDetailTotalPrice { get; set; }
        public string ProductCommercialName { get; set; }
        public string Customer { get; set; }
        public string CardSerialNumber { get; set; }
        public string TicketSerialNumber { get; set; }
    }
}
