//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionMaintenance
    {
        public long Id { get; set; }
        public int ProgressiveNumber { get; set; }
        public System.DateTime Date { get; set; }
        public byte MaintenanceActionId { get; set; }
        public string Notes { get; set; }
        public long SessionId { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] RV { get; set; }
    
        public virtual MaintenanceAction MaintenanceAction { get; set; }
        public virtual Session Session { get; set; }
    }
}
