//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockEntity()
        {
            this.StockEntityDetail = new HashSet<StockEntityDetail>();
            this.StockMovement = new HashSet<StockMovement>();
            this.StockMovement1 = new HashSet<StockMovement>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public long TypeId { get; set; }
        public Nullable<long> OperatorId { get; set; }
        public Nullable<long> DeviceId { get; set; }
        public Nullable<long> LocationId { get; set; }
        public bool IsDefaultFrom { get; set; }
        public bool IsDefaultTo { get; set; }
        public bool IsDiscarded { get; set; }
        public bool IsCirculating { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsNative { get; set; }
        public byte[] RV { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Location Location { get; set; }
        public virtual Operator Operator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockEntityDetail> StockEntityDetail { get; set; }
        public virtual StockEntityType StockEntityType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockMovement> StockMovement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockMovement> StockMovement1 { get; set; }
    }
}
