//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMovement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockMovement()
        {
            this.Card = new HashSet<Card>();
            this.Ticket = new HashSet<Ticket>();
        }
    
        public long Id { get; set; }
        public long FromStockEntityId { get; set; }
        public long ToStockEntityId { get; set; }
        public long InventoryItemId { get; set; }
        public Nullable<long> StockItemId { get; set; }
        public Nullable<long> ProviderId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsSupply { get; set; }
        public long StockMovementStatusId { get; set; }
        public string Description { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] RV { get; set; }
    
        public virtual InventoryItem InventoryItem { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual StockEntity StockEntity { get; set; }
        public virtual StockEntity StockEntity1 { get; set; }
        public virtual StockItem StockItem { get; set; }
        public virtual StockMovementStatus StockMovementStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card> Card { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
