//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransCityParameter
    {
        public long Id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string StringValue { get; set; }
        public Nullable<long> LongValue { get; set; }
        public Nullable<double> DoubleValue { get; set; }
        public bool IsMutable { get; set; }
        public System.DateTime InsDate { get; set; }
        public long InsOperId { get; set; }
        public byte[] RV { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
    }
}
