//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel
    {
        public long Id { get; set; }
        public string Service { get; set; }
        public bool IsReturnTrip { get; set; }
        public Nullable<long> ItineraryId { get; set; }
        public Nullable<System.DateTime> DepartureTime { get; set; }
        public bool IsAfterMidnight { get; set; }
        public Nullable<long> SchedulePeriod { get; set; }
        public Nullable<long> DayType { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
        public Nullable<long> InsOperId { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsHidden { get; set; }
        public byte[] RV { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
    
        public virtual Itinerary Itinerary { get; set; }
    }
}
