//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Validation
    {
        public long Id { get; set; }
        public long SessionId { get; set; }
        public long TCN { get; set; }
        public Nullable<long> FareProductItemId { get; set; }
        public long ProductIssuerId { get; set; }
        public long OperatorId { get; set; }
        public int TripCounterBeforeValidation { get; set; }
        public int TripCounterAfterValidation { get; set; }
        public int ValidationNumber { get; set; }
        public Nullable<long> VehicleId { get; set; }
        public Nullable<long> LineId { get; set; }
        public Nullable<long> ItineraryId { get; set; }
        public int Direction { get; set; }
        public Nullable<long> FareStopId { get; set; }
        public System.DateTime ValidationDate { get; set; }
        public Nullable<long> CardId { get; set; }
        public Nullable<long> TicketId { get; set; }
        public long ValidationStatusId { get; set; }
        public long FailureReasonId { get; set; }
        public System.DateTime ContractValidityEndDate { get; set; }
        public int ValidationStateId { get; set; }
        public Nullable<System.DateTime> ProductStartValidity { get; set; }
        public Nullable<System.DateTime> ProductEndOfValidity { get; set; }
        public Nullable<long> UnknowProductId { get; set; }
        public byte[] RV { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
        public Nullable<long> InsOperId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<long> ModOperId { get; set; }
        public bool IsHashed { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual ValidationRejectReason ValidationRejectReason { get; set; }
        public virtual ValidationStatus ValidationStatus { get; set; }
    }
}
