//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwAutomaticPayment
    {
        public long PlanId { get; set; }
        public long PlanStatusId { get; set; }
        public string PlanStatusCode { get; set; }
        public string Rum { get; set; }
        public long IbanId { get; set; }
        public string IBAN { get; set; }
        public long PayerId { get; set; }
        public string PayerFirstName { get; set; }
        public string PayerLastName { get; set; }
        public Nullable<long> AnnexPayerId { get; set; }
        public Nullable<long> AnnexPayerIbanId { get; set; }
        public string AnnexPayerIBAN { get; set; }
        public Nullable<System.DateTime> RejectDate { get; set; }
        public int PaymentAmount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public long InstallementId { get; set; }
        public Nullable<long> InstallmentRejectReasonId { get; set; }
        public string InstallmentRejectReasonCode { get; set; }
        public long InstallmentStatusId { get; set; }
        public string InstallmentStatusCode { get; set; }
        public Nullable<long> InstallmentStatusReasonId { get; set; }
        public string InstallmentStatusReasonCode { get; set; }
        public string ContractDescription { get; set; }
        public string LanguageCode { get; set; }
        public string CardSerialNumber { get; set; }
        public string HolderFirstname { get; set; }
        public string HolderLastName { get; set; }
        public long HolderId { get; set; }
        public bool IsRenewable { get; set; }
    }
}
