//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwTaciteReconduction
    {
        public long PlanId { get; set; }
        public Nullable<long> ConfigurationId { get; set; }
        public bool IsRenewable { get; set; }
        public Nullable<System.DateTime> EndValidityDate { get; set; }
        public long PlanStatusId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string Rum { get; set; }
        public long PaymentOrderId { get; set; }
        public long FareProductItemId { get; set; }
        public long FareVersionId { get; set; }
        public long ProductId { get; set; }
        public long ProductCode { get; set; }
        public Nullable<long> PeriodTypeId { get; set; }
        public Nullable<long> CardId { get; set; }
        public Nullable<System.DateTime> ProductStartValidity { get; set; }
        public Nullable<System.DateTime> ProductEndOfValidity { get; set; }
        public long Tcn { get; set; }
    }
}
