//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwTitanRecettePayment
    {
        public long SaleId { get; set; }
        public long TransactionNumber { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public long CodeProduct { get; set; }
        public Nullable<long> SaleDetailTypeId { get; set; }
        public Nullable<long> AnnexProductTypeId { get; set; }
        public Nullable<long> PaymentMethodId { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<long> DeviceId { get; set; }
        public int PaymentAmount { get; set; }
        public int PaymentReturn { get; set; }
        public Nullable<long> TicketPrejudiceId { get; set; }
        public Nullable<int> DeviceNumber { get; set; }
        public string DeviceType { get; set; }
        public Nullable<long> DeviceTypeId { get; set; }
        public int SessionNumber { get; set; }
        public Nullable<long> OperatorSerialNumber { get; set; }
        public int NumberOfProductSold { get; set; }
        public int PriceSale { get; set; }
        public int WasRejected { get; set; }
    }
}
