//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwTitanRecetteSale
    {
        public long SaleId { get; set; }
        public long TransactionNumber { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<long> DeviceId { get; set; }
        public string Device { get; set; }
        public Nullable<int> DeviceNumber { get; set; }
        public Nullable<long> DeviceTypeId { get; set; }
        public string DeviceType { get; set; }
        public int SessionNumber { get; set; }
        public Nullable<long> OperatorSerialNumber { get; set; }
        public Nullable<long> AnnexProductTypeId { get; set; }
        public Nullable<long> SaleDetailStatusId { get; set; }
        public Nullable<long> SaleDetailTypeId { get; set; }
        public int SaleNumberOfRequestedProducts { get; set; }
        public int SaleNumberOfDeliveredProducts { get; set; }
        public int SaleAmountOfDamagedTickets { get; set; }
        public Nullable<int> NumberOfProductSold { get; set; }
        public Nullable<int> NumberOfProductDelivered { get; set; }
        public int PriceSale { get; set; }
        public Nullable<int> UnitPrice { get; set; }
        public int SaleTotalAmount { get; set; }
        public Nullable<System.DateTime> ProductStartValidity { get; set; }
        public Nullable<System.DateTime> ProductEndOfValidity { get; set; }
        public Nullable<bool> IsRefound { get; set; }
        public long CodeProduct { get; set; }
        public Nullable<long> MonthlyAnnexProductId { get; set; }
        public string ReductionCode { get; set; }
        public Nullable<int> ReductionAmount { get; set; }
        public int HasInstallment { get; set; }
        public int WasRejected { get; set; }
    }
}
