//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwVcub
    {
        public long CustomerId { get; set; }
        public Nullable<int> Age { get; set; }
        public long CardId { get; set; }
        public string CardSerialNumber { get; set; }
        public Nullable<long> CardTypeId { get; set; }
        public string CardType { get; set; }
        public Nullable<System.DateTime> CardCreationDate { get; set; }
        public string Code { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public long CompanyCode { get; set; }
    }
}
